baseURL: "https://www.example.com/"
theme: "up-business-theme"
languageCode: "en-us"

title: "Borneo IoT"

googleAnalytics: "G-HPQMWJZL8M"

summaryLength: 20

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      footnote: true

params:
  title: "Borneo IoT"
  description: "An open source full-stack LED and other smart IoT kits for aquarium."
  images:
    - "images/borneo-hero.jpg"

  logo: "logo.png"

  cover:
    hidden: false # hide everywhere but not in structured data

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    #dribbble: "#"
    #instagram: "#"
    github: "https://github.com/oldrev/borneo"
    twitter: "https://x.com/oldrev"

  location:
    - "TBD"

  contact:
    - "E-mail: oldrev@gmail.com"

  copyright: "Copyright © Li Wei. All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

#    - name: "How we work"
#      url: "/#"
#      weight: 2

#    - name: "Our team"
#      url: "/#"
#      weight: 3

#    - name: "Pricing"
#      url: "/#"
#      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

    - name: "Documentation"
      url: "https://docs.borneoiot.com"
      weight: 9

    - name: "About"
      url: "/homepage/about"
      weight: 10

  buttons:
    - name: "View in GitHub"
      url: "https://github.com/oldrev/borneo"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

#    - name: "How we work"
#      url: "/#"
#      weight: 2

#    - name: "Our team"
#      url: "/#"
#      weight: 3

#    - name: "Pricing"
#      url: "/#"
#      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

    - name: "Documentation"
      url: "https://docs.borneoiot.com"
      weight: 9

    - name: "About"
      url: "/homepage/about"
      weight: 10

taxonomies:
  series: "series"
  tags: "tags"
  year: "year"
  month: "month"
