baseURL: https://www.borneoiot.com
theme: hugobricks
defaultContentLanguage: en
assetDir: static

params:
  googleAnalytics: "G-HPQMWJZL8M"


markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      extras:
        insert:
          enable: true
        mark:
          enable: true
        subscript:
          enable: true
        superscript:
          enable: true

languages:
  en:
    languageName: English
    contentDir: content/en
    weight: 1
    disabled: false
    permalinks:
      page:
        posts: /blog/:year:month/:slug
        services: /services/:slug
        products: /webshop/:slug
      section:
        posts: /blog/
        services: /services/
        products: /webshop/

  # zh:
  #   languageName: 简体中文
  #   contentDir: content/zh
  #   weight: 2
  #   disabled: false
  #   permalinks:
  #     page:
  #       posts: /blog/:slug
  #       services: /diensten/:slug
  #       products: /winkel/:slug
  #     section:
  #       posts: /blog/
  #       services: /diensten/
  #       products: /winkel/


taxonomies:
  series: "series"
  tags: "tags"
  year: "year"
  month: "month"