baseURL: "https://www.example.com/"
theme: "up-business-theme"
languageCode: "en-us"

title: "Borneo IoT"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Borneo IoT"
  description: "A based open-source full-stack LED lighting and other automated smart IoT solutions for aquariums."
  images:
    - "images/hero-image.jpg"

  logo: "logo.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    #dribbble: "#"
    #instagram: "#"
    github: "https://github.com/oldrev/borneo"
    twitter: "https://x.com/oldrev"

  location:
    - "TBD"

  contact:
    - "oldrev@gmail.com"

  copyright: "Copyright © Li Wei. All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

#    - name: "How we work"
#      url: "/#"
#      weight: 2

#    - name: "Our team"
#      url: "/#"
#      weight: 3

#    - name: "Pricing"
#      url: "/#"
#      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

    - name: "About"
      url: "/about"
      weight: 10

  buttons:
    - name: "View in GitHub"
      url: "https://github.com/oldrev/borneo"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

#    - name: "How we work"
#      url: "/#"
#      weight: 2

#    - name: "Our team"
#      url: "/#"
#      weight: 3

#    - name: "Pricing"
#      url: "/#"
#      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
